name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build & test"
        run: |
          sudo rm -rf deb_dist
          sudo apt-get install -y debhelper
          sudo python3 -m pip install pip setuptools wheel 
          sudo apt install -y build-essential python3-dev python3-setuptools
          sudo -H python3 -m pip install stdeb
          sudo apt-get install -y fakeroot python3-all git
          sudo apt install dh-python
          cp setup.py setup1.py
          cp setup_debian.py setup.py
          sudo python3 setup.py --command-packages=stdeb.command bdist_deb
          cp setup1.py setup.py
          echo "done!"
      - name: Check if pre-release exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: 'pre-release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete current pre-release
        if:  failure() && steps.checkTag.outputs.exists == 'true'
        uses: author/action-rollback@stable
        with:
          tag: 'pre-release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload debian to pre-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deb_dist/*.deb
          tag: "pre-release"
          overwrite: true
          file_glob: true
